; -- configs --
; [_configs_]

; -- repository definitions --
; Use [_repos_] as a marker for repository sections
[_repos_]

[packages]
_ = https://github.com/xj11400/.dotfiles.git
zsh = https://github.com/xj11400/dot-custom.git
nvim = https://github.com/xj11400/dot-custom.git
tmux = https://github.com/xj11400/dot-custom.git
; Branch/Tag support
dev = https://github.com/xj11400/dot-custom.git --branch=dev

[custom]
_ = https://github.com/xj11400/dot-custom.git
foo = https://github.com/xj11400/dot-custom.git
bar = https://github.com/xj11400/dot-custom.git

[repo_only]
_ = https://github.com/xj11400/dot-custom.git

[folder_only]
xxx = https://github.com/xj11400/dot-custom.git

; -- symlink scopes (tasks) --
; Each section following [_symlinks_] is an independent task.
[_symlinks_]

[main]
; Options (always put options before link rules)
target_dir = $HOME
; pkg_dirs: directories to scan for packages.
; - directories starting with '_' or '.' are ignored by default.
; - use '_' to scan the root dotfiles directory.
; - add '_user' directory to scan.
pkg_dirs = _, _user
; silent = true ; skip interactive selection for this task

; Link Rules
; Format: group = [options |] item1, item2, ...
; Options: --skip (skip existing), --files (link files inside dir), --resymlink (force)

; Items from root ('_')
_ = --skip | lazygit, ranger, tmux, zsh
_ = --files | fsh, git

; Items from '_user' directory
_user = --files | nvim, ssh

[link_to_local]
target_dir = $HOME/.local
pkg_dirs = _unused
_unused = --files | warp

[other_task]
target_dir = $HOME/.local/bin
; scan root for 'utils'
pkg_dirs = _
_ = utils
